apiVersion: v1
kind: Service
metadata:
  labels:
    app: rails-service
  name: rails-service
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32730
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: rails
  type: NodePort